# Generated by Django 4.1.7 on 2023-03-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_description_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
