# Generated by Django 4.1.7 on 2023-03-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_active_alter_product_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
